### ISSUE TITLE
Make the global flag optional

### ISSUE THREAD

**Issue by kudapara** [michaeldera/simple-regex#8]
There are scenarios when the SimpleRegex tests will be run multiple times, for example, testing phone numbers during typing, after a user blurs input and just before sending an HTTP request to the server.

In these scenarios, the regex test return alternating results for the exact same phone number. After doing some digging ([thanks to stack overflow](https://stackoverflow.com/questions/20463349/why-the-results-from-running-exactly-the-same-regular-expression-twice-are-diffe)), I realized that the global regex search starts from the previous match for each invocation of .test and that causes subsequent tests to have a different result even with the same input.

Example: Running `SimpleRegex.MobileNumber.Econet.test(phoneNumber)` twice, gives you different results

I would like to have an option to remove the global matching of the regexes.

**Comment by michaeldera** [comment]
Thank you @kudapara. I really ought to have considered this in terms of the documentation bit. So that behaviour is becuase I added the global flag on the Regex pattern. The flag is useful for cases where you want to search for multiple occurrences of a pattern within a large string. More on that [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) 

So my thoughts are that we probably forgo the global flag altogether and allow package users to be able to add it if they are doing search on a paragraph. Maybe something like this: 

`const regexWithGlobalFlag = RegExp( SimpleRegex.MobileNumber +'/gm' )`....  the new `regexWithGlobalFlag` could then be used to do searches where all occurrences of the string need to be found.

I think this would keep the package small and simple while providing convenience for users but I am open to hearing from people using the package and see what they prefer so I will invite people to discuss this.
